exceptions:
  - url: https://www.bugseng.com/filebrowser/download/32
    code: HTTP_403

  - url: https://www.bugseng.com/filebrowser/download/38
    code: HTTP_403

  - url: https://www.fastcompany.com/28121/they-write-right-stuff
    code: HTTP_403

  - url: https://www.railjournal.com/in_depth/white-paper-achieving-compliance-with-en-50128
    code: HTTP_403

  - url: https://www.osti.gov/scitech/servlets/purl/184397
    code: SSL_ERROR

  # This resource has been quite unstable. Check this after some time.
  - url: https://swehb.nasa.gov/display/SWEHBVC/Book+A.+Introduction
    code: HTTP_5xx

  # Failed link: Status.SSL_ERROR
  # HTTPSConnectionPool(host='inis.iaea.org', port=443)
  # The link opens itself in the browser though.
  - url: https://inis.iaea.org/collection/NCLCollectionStore/_Public/25/062/25062186.pdf
    code: SSL_ERROR
